  
	
	-- =================================================  
	--   CORE SERVIES 
	--   TASK 
	-- =================================================	
	
	CREATE TABLE AC_TASK (
		OBJECT_TYPE			INTEGER NOT NULL,
		OBJECT_ID			INTEGER NOT NULL,	
		TASK_ID					INTEGER NOT NULL,
		TASK_NAME				VARCHAR2(255) NOT NULL,
		VERSION					VARCHAR2(255),
		DESCRIPTION				VARCHAR2(1000),
		PROGRESS				VARCHAR2(255),
		PRICE					NUMBER DEFAULT 0,	
		START_DATE				DATE,
		END_DATE				DATE,			
		USER_ID					INTEGER NOT NULL,
		CREATION_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		MODIFIED_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		CONSTRAINT AC_TASK_PK PRIMARY KEY (TASK_ID)
	);	 
	
	COMMENT ON TABLE  "AC_TASK"  IS 'TASK 테이블';
	COMMENT ON COLUMN "AC_TASK"."TASK_ID" IS 'TASK ID'; 
	COMMENT ON COLUMN "AC_TASK"."TASK_NAME" IS 'TASK 이름'; 
	COMMENT ON COLUMN "AC_TASK"."VERSION" IS 'TASK 버전'; 
	COMMENT ON COLUMN "AC_TASK"."DESCRIPTION" IS 'TASK 설명'; 
	COMMENT ON COLUMN "AC_TASK"."PROGRESS" IS '진행율'; 
	COMMENT ON COLUMN "AC_TASK"."USER_ID" IS '생성자'; 
	COMMENT ON COLUMN "AC_TASK"."CREATION_DATE" IS '생성일'; 
	COMMENT ON COLUMN "AC_TASK"."MODIFIED_DATE" IS '수정일'; 	
	
	CREATE INDEX AC_TASK_IDX_01 ON AC_TASK (OBJECT_TYPE, OBJECT_ID);

	CREATE TABLE "AC_TASK_PROPERTY" (	
	"TASK_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PROPERTY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PROPERTY_VALUE" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	CONSTRAINT "AC_TASK_PROPERTY_PK" PRIMARY KEY ("TASK_ID", "PROPERTY_NAME"));
 

	COMMENT ON COLUMN "AC_TASK_PROPERTY"."TASK_ID" IS 'TASK ID'; 
	COMMENT ON COLUMN "AC_TASK_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
	COMMENT ON COLUMN "AC_TASK_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 
	COMMENT ON TABLE  "AC_TASK_PROPERTY"  IS 'TASK 프로퍼티 테이블';	
		