	-- =================================================  
	--  UI SCRIPT OR TEMPLETE SOURCE	
	-- =================================================	
	
	CREATE TABLE AC_UI_SCRIPT_SOURCE
		SOURCE_ID					INTEGER NOT NULL,
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID					INTEGER NOT NULL,		
		SOURCE_TYPE					INTEGER NOT NULL,
		SOURCE_TEXT					CLOB,
		CREATION_DATE				DATE DEFAULT  SYSDATE NOT NULL,
		MODIFIED_DATE				DATE DEFAULT  SYSDATE NOT NULL,
		CONSTRAINT AC_UI_SCRIPT_SOURCE_PK PRIMARY KEY (SOURCE_ID)
	);
	
	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : API 
	-- CREATE : 2018.10.18
	-- UPDATE : 
	-- =================================================		
	CREATE TABLE AC_UI_API (
		OBJECT_TYPE				INTEGER NOT NULL,
		OBJECT_ID				INTEGER NOT NULL,	
		
		API_ID					INTEGER NOT NULL,
		TITLE				VARCHAR2(255), 
		API_NAME				VARCHAR2(255) NOT NULL,
		API_VERSION				VARCHAR2(255) NOT NULL,
		DESCRIPTION				VARCHAR2(1000),
		
		CONTENT_TYPE			VARCHAR2(50), 
		SECURED					NUMBER(1, 0)  DEFAULT 1,
		ENABLED					NUMBER DEFAULT 0,	
		SCRIPT					VARCHAR2(255), 
		PATTERN					VARCHAR2(255), 
		CREATOR_ID				INTEGER NOT NULL,
		CREATION_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		MODIFIED_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_API_PK PRIMARY KEY (API_ID)
	);	
	
	CREATE INDEX AC_UI_API_IDX_01 ON AC_UI_API (OBJECT_TYPE, OBJECT_ID);

	CREATE TABLE "AC_UI_API_PROPERTY" (	
	"API_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PROPERTY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PROPERTY_VALUE" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	CONSTRAINT "AC_UI_API_PROPERTY_PK" PRIMARY KEY ("API_ID", "PROPERTY_NAME"));

	COMMENT ON COLUMN "AC_UI_API_PROPERTY"."API_ID" IS 'TASK ID'; 
	COMMENT ON COLUMN "AC_UI_API_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
	COMMENT ON COLUMN "AC_UI_API_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 
	COMMENT ON TABLE  "AC_UI_API_PROPERTY"  IS 'TASK 프로퍼티 테이블';	
	
	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : PAGE 
	-- CREATE : 2018.09.19
	-- UPDATE :
	-- 2018.09.17 - AC_UI_PAGE_BODY_VERSION.SCRIPT 추가 
	-- =================================================	
	CREATE TABLE AC_UI_PAGE(	
		PAGE_ID						INTEGER NOT NULL,
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID					INTEGER NOT NULL,
		NAME						VARCHAR2(255) NOT NULL,	
		VERSION_ID					INTEGER DEFAULT 1 NOT NULL,
		USER_ID						INTEGER NOT NULL,
		READ_COUNT          			INTEGER DEFAULT 0  NOT NULL,
		CREATION_DATE				DATE DEFAULT  SYSDATE NOT NULL,
		MODIFIED_DATE				DATE DEFAULT  SYSDATE NOT NULL,			
		CONSTRAINT AC_UI_PAGE_PK PRIMARY KEY (PAGE_ID)
	);

	CREATE UNIQUE INDEX AC_UI_PAGE_IDX1 ON REP_PAGE (NAME);
	CREATE INDEX AC_UI_PAGE_IDX2   ON REP_PAGE (OBJECT_TYPE, OBJECT_ID, PAGE_ID);
	CREATE INDEX AC_UI_PAGE_IDX3   ON REP_PAGE (USER_ID);

	CREATE TABLE AC_UI_PAGE_BODY
	(	
		BODY_ID						INTEGER NOT NULL,
		PAGE_ID						INTEGER NOT NULL,
		BODY_TYPE					INTEGER NOT NULL,
		BODY_TEXT					CLOB,
		CONSTRAINT AC_UI_PAGE_BODY_PK PRIMARY KEY (BODY_ID)
    ) ;
	
		
	CREATE TABLE AC_UI_PAGE_BODY_VERSION
	(	
		BODY_ID					INTEGER NOT NULL,
		PAGE_ID						INTEGER NOT NULL,
		VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
		CONSTRAINT AC_UI_PAGE_BODY_VERSION_PK PRIMARY KEY (BODY_ID, PAGE_ID, VERSION_ID )
   );
   
   CREATE INDEX AC_UI_PAGE_BODY_VERSION_IDX1   ON AC_UI_PAGE_BODY_VERSION (PAGE_ID, VERSION_ID);

		
  CREATE TABLE AC_UI_PAGE_VERSION
   (	
	PAGE_ID					INTEGER NOT NULL,
	VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
	STATE					VARCHAR2(20), 
	TITLE					VARCHAR2(255), 
	SECURED          		NUMBER(1, 0)  DEFAULT 1,
	TEMPLATE				VARCHAR2(255), 
	SCRIPT					VARCHAR2(255), 
	PATTERN					VARCHAR2(255), 	
	SUMMARY					VARCHAR2(4000), 
	USER_ID					INTEGER	NOT NULL,
	CREATION_DATE			DATE DEFAULT  SYSDATE NOT NULL,
	MODIFIED_DATE			DATE DEFAULT  SYSDATE NOT NULL,	
	CONSTRAINT AC_UI_PAGE_VERSION_PK PRIMARY KEY (PAGE_ID, VERSION_ID)
   ) ;

		
	CREATE INDEX AC_UI_PAGE_VERSION_IDX1   ON AC_UI_PAGE_VERSION (CREATION_DATE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX2   ON AC_UI_PAGE_VERSION (MODIFIED_DATE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX3   ON AC_UI_PAGE_VERSION (TITLE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX4   ON AC_UI_PAGE_VERSION (PAGE_ID, STATE);

			
	CREATE TABLE AC_UI_PAGE_PROPERTY (
		  PAGE_ID				INTEGER NOT NULL,
		  VERSION_ID				INTEGER DEFAULT 1 NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT AC_UI_PAGE_PROPERTY_PK PRIMARY KEY (PAGE_ID, VERSION_ID, PROPERTY_NAME)
	);	

	COMMENT ON TABLE  "AC_UI_PAGE_PROPERTY"  IS 'PAGE 프로퍼티 테이블';
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."PAGE_ID" IS 'PAGE ID'; 
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."VERSION_ID" IS 'PAGE VERSION'; 	
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
	COMMENT ON COLUMN "AC_UI_PAGE_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 	 
	
	-- =================================================  
	--  UI CONTACTS	
	-- =================================================	
	CREATE TABLE AC_UI_CONTACT (
		CONTACT_ID				INTEGER NOT NULL,
		COMPANY_NAME			VARCHAR2(255) NOT NULL,
		JOB_TITLE				VARCHAR2(500) NOT NULL,
		NAME					VARCHAR2(255) NOT NULL,
		EMAIL					VARCHAR2(255) NOT NULL,
		TELEPHONE				VARCHAR2(255) NOT NULL,
		MOBILEPHONE				VARCHAR2(255) NOT NULL,
		NOTE					VARCHAR2(4000),
		CREATION_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		MODIFIED_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_CONTACT_PK PRIMARY KEY (CONTACT_ID)
	);	
	
	
	CREATE TABLE AC_UI_CALENDAR (
		CALENDAR_ID				INTEGER NOT NULL,
		CALENDAR_NAME			VARCHAR2(255) NOT NULL,
		TIMEZONE				VARCHAR2(500) NOT NULL,
		DESCRIPTION				VARCHAR2(4000),
		USER_ID					INTEGER NOT NULL,
		CREATION_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		MODIFIED_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_CALENDAR_PK PRIMARY KEY (CALENDAR_ID)
	);	
		