	-- =================================================  
	--  UI CONTACTS	
	-- =================================================	
	CREATE TABLE AC_UI_CONTACT (
		CONTACT_ID				INTEGER NOT NULL,
		COMPANY_NAME			VARCHAR2(255) NOT NULL,
		JOB_TITLE				VARCHAR2(500) NOT NULL,
		NAME					VARCHAR2(255) NOT NULL,
		EMAIL					VARCHAR2(255) NOT NULL,
		TELEPHONE				VARCHAR2(255) NOT NULL,
		MOBILEPHONE				VARCHAR2(255) NOT NULL,
		NOTE					VARCHAR2(4000),
		CREATION_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		MODIFIED_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_CONTACT_PK PRIMARY KEY (CONTACT_ID)
	);	
	
	
	CREATE TABLE AC_UI_CALENDAR (
		CALENDAR_ID				INTEGER NOT NULL,
		CALENDAR_NAME			VARCHAR2(255) NOT NULL,
		TIMEZONE				VARCHAR2(500) NOT NULL,
		DESCRIPTION				VARCHAR2(4000),
		USER_ID					INTEGER NOT NULL,
		CREATION_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		MODIFIED_DATE			TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_CALENDAR_PK PRIMARY KEY (CALENDAR_ID)
	);	
		